export const PREDEFINED_SKILLS = [
    // Computer Science, Software & AI
    "Algorithms & Data Structures",
    "Artificial Intelligence",
    "AWS (Amazon Web Services)",
    "Backend Development",
    "Bioinformatics",
    "C++",
    "Cybersecurity",
    "Cloud Computing",
    "Computer Vision",
    "CI/CD (Continuous Integration/Continuous Deployment)",
    "Database Management",
    "DevOps",
    "Deep Learning",
    "Docker",
    "E-commerce",
    "Figma",
    "Firebase",
    "Flutter",
    "Frontend Development",
    "Fullstack Development",
    "Git & Version Control",
    "Go (Golang)",
    "HTML & CSS",
    "Intellectual Property",
    "Java",
    "JavaScript",
    "Kotlin",
    "Kubernetes",
    "Linux Systems",
    "Machine Learning",
    "Mobile App Development",
    "MongoDB",
    "Natural Language Processing (NLP)",
    "Next.js",
    "Node.js",
    "NoSQL Databases",
    "PHP",
    "PostgreSQL",
    "Python",
    "React",
    "React Native",
    "Ruby on Rails",
    "Rust",
    "SQL",
    "Swift",
    "Tailwind CSS",
    "TypeScript",
    "UI/UX Design",
    "Web Development",

    // Engineering & Physical Sciences
    "Aerospace Engineering",
    "Arduino & Microcontrollers",
    "CAD (Computer-Aided Design)",
    "Chemical Engineering",
    "Circuit Design",
    "Civil Engineering",
    "Control Systems",
    "Electrical Engineering",
    "Embedded Systems",
    "Fluid Mechanics",
    "LabVIEW",
    "Materials Science",
    "MATLAB",
    "Mechanical Engineering",
    "Nanotechnology",
    "Raspberry Pi",
    "Robotics",
    "SolidWorks",
    "Structural Analysis",
    "Thermodynamics",

    // Health, Medicine & Biology
    "Anatomy & Physiology",
    "Biochemistry",
    "Clinical Research",
    "Dentistry",
    "Epidemiology",
    "Genomics",
    "Immunology",
    "Medical Imaging",
    "Molecular Biology",
    "Neuroscience",
    "Nursing Care",
    "Pathology",
    "Pharmacology",
    "Pharmacy Practice",
    "Public Health",

    // Business, Marketing & Management
    "Accounting",
    "Agile & Scrum",
    "Budget Management",
    "Business Development",
    "Business Strategy",
    "Change Management",
    "Corporate Finance",
    "CRM (Salesforce)",
    "Cross-functional Team Leadership",
    "Digital Marketing",
    "Entrepreneurship",
    "Financial Analysis",
    "Growth Hacking",
    "Market Research",
    "Operations Management",
    "Performance Management",
    "Product Management",
    "Project Management",
    "Resource Allocation",
    "Risk Management",
    "SEO (Search Engine Optimization)",
    "Sales & Negotiation",
    "Stakeholder Management",
    "Strategic Planning",
    "Team Leadership",
    "Venture Capital",

    // Humanities & Social Sciences
    "Anthropology",
    "Copywriting",
    "Creative Writing",
    "Econometrics",
    "Economics",
    "Editing & Proofreading",
    "History",
    "Journalism",
    "Legal Writing",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Public Relations",
    "Sociology",
    "Technical Writing",
    "Translation & Localization",

    // Natural Sciences & Mathematics
    "Astronomy",
    "Calculus",
    "Chemistry",
    "Data Analysis",
    "Data Science",
    "Ecology & Conservation",
    "Environmental Science",
    "Geology",
    "GIS (Geographic Information Systems)",
    "Linear Algebra",
    "Mathematics",
    "Organic Chemistry",
    "Physics",
    "Probability",
    "R Programming",
    "Statistics",

    // Design & Arts
    "3D Modeling",
    "Adobe After Effects",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Adobe Premiere Pro",
    "Animation",
    "Blender",
    "Filmmaking & Videography",
    "Graphic Design",
    "Illustration",
    "Motion Graphics",
    "Painting & Fine Arts",
    "Photography",

    // Education, Communication & Soft Skills
    "Academic Research",
    "Active Listening",
    "Adaptability & Flexibility",
    "Collaboration & Teamwork",
    "Conflict Resolution",
    "Creative Thinking",
    "Critical Thinking",
    "Curriculum Development",
    "Decision Making",
    "E-Learning",
    "Emotional Intelligence",
    "Empathy",
    "Instructional Design",
    "Interpersonal Skills",
    "Language Teaching",
    "Mentoring & Coaching",
    "Presentation Design",
    "Problem Solving",
    "Public Speaking",
    "Time Management",
    "Work Ethic"
];
